name: Publish Nuget Package
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'Nick.RobotsParser/**'
jobs:
  Publish-Nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet pack -c Release
    - name: Push to Nuget
      run: dotnet nuget push ./Robots/bin/Release/RobotsSharpParser.2.0.2.nupkg --api-key ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
    - name: Clean
      run: dotnet clean
